/**
 * Code Generation IORS Tools
 * Phase 2: Full-stack app generation, code modification, testing, deployment
 *
 * Tools:
 * - generate_fullstack_app: Multi-file app generation (React + API + DB)
 * - modify_code: Edit existing code files via AI
 * - run_tests: AI-generated test analysis (no Docker execution)
 * - deploy_app: Deploy to Vercel or return manual instructions
 */

import type { ToolDefinition } from "./shared";
import type { CodeGenerationTask } from "@/lib/code-generation/types";
import { executeCodeGeneration } from "@/lib/code-generation/executor";
import {
  isVPSAvailable,
  executeOnVPS,
  runTestsOnVPS,
  formatVPSResult,
} from "@/lib/code-generation/vps-executor";
import { buildFullStackApp } from "@/lib/code-generation/full-stack-builder";
import {
  type InfraService,
  getInfraGuide,
  formatInfraGuide,
  formatInfraOverview,
} from "@/lib/code-generation/infra-helper";

import { logger } from "@/lib/logger";

// ============================================================================
// SCAFFOLD TEMPLATES
// ============================================================================

function generateScaffold(
  name: string,
  template: string,
  features: string[],
): Array<{ path: string; content: string; language: string }> {
  const hasAuth = features.includes("auth");
  const hasDashboard = features.includes("dashboard");
  const hasApi = features.includes("api");

  const files: Array<{ path: string; content: string; language: string }> = [];

  // package.json
  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name,
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          next: "^15.0.0",
          react: "^19.0.0",
          "react-dom": "^19.0.0",
          ...(template !== "api-only"
            ? { tailwindcss: "^4.0.0", "@tailwindcss/postcss": "^4.0.0" }
            : {}),
          ...(template === "nextjs-supabase"
            ? { "@supabase/supabase-js": "^2.45.0", "@supabase/ssr": "^0.5.0" }
            : {}),
        },
        devDependencies: {
          typescript: "^5.6.0",
          "@types/node": "^22.0.0",
          "@types/react": "^19.0.0",
        },
      },
      null,
      2,
    ),
    language: "json",
  });

  // tsconfig.json
  files.push({
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"],
      },
      null,
      2,
    ),
    language: "json",
  });

  // .env.local.example
  const envVars = ["# App\nNEXT_PUBLIC_APP_URL=http://localhost:3000"];
  if (template === "nextjs-supabase") {
    envVars.push(
      "# Supabase\nNEXT_PUBLIC_SUPABASE_URL=\nNEXT_PUBLIC_SUPABASE_ANON_KEY=\nSUPABASE_SERVICE_ROLE_KEY=",
    );
  }
  files.push({
    path: ".env.local.example",
    content: envVars.join("\n\n"),
    language: "env",
  });

  // app/layout.tsx
  files.push({
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next";
${template !== "api-only" ? 'import "./globals.css";' : ""}

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by ExoSkull",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pl">
      <body>{children}</body>
    </html>
  );
}
`,
    language: "typescript",
  });

  // app/page.tsx
  files.push({
    path: "app/page.tsx",
    content: `export default function HomePage() {
  return (
    <main className="flex min-h-screen items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold">${name}</h1>
        <p className="mt-4 text-gray-600">Twoja aplikacja jest gotowa.</p>
${hasAuth ? '        <a href="/login" className="mt-6 inline-block rounded bg-blue-600 px-6 py-2 text-white hover:bg-blue-700">Zaloguj się</a>' : ""}
      </div>
    </main>
  );
}
`,
    language: "typescript",
  });

  if (template !== "api-only") {
    // globals.css
    files.push({
      path: "app/globals.css",
      content: `@import "tailwindcss";
`,
      language: "css",
    });
  }

  if (hasAuth && template === "nextjs-supabase") {
    files.push({
      path: "app/login/page.tsx",
      content: `"use client";

import { useState } from "react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault();
    // TODO: Implement Supabase auth
  }

  return (
    <main className="flex min-h-screen items-center justify-center">
      <form onSubmit={handleLogin} className="w-full max-w-sm space-y-4">
        <h1 className="text-2xl font-bold">Logowanie</h1>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className="w-full rounded border p-2"
          required
        />
        <input
          type="password"
          placeholder="Hasło"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className="w-full rounded border p-2"
          required
        />
        <button type="submit" className="w-full rounded bg-blue-600 py-2 text-white hover:bg-blue-700">
          Zaloguj się
        </button>
      </form>
    </main>
  );
}
`,
      language: "typescript",
    });
  }

  if (hasDashboard) {
    files.push({
      path: "app/dashboard/page.tsx",
      content: `export default function DashboardPage() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold">Dashboard</h1>
      <p className="mt-2 text-gray-600">Witaj w panelu.</p>
    </main>
  );
}
`,
      language: "typescript",
    });
  }

  if (hasApi || template === "api-only") {
    files.push({
      path: "app/api/health/route.ts",
      content: `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({ status: "ok", timestamp: new Date().toISOString() });
}
`,
      language: "typescript",
    });
  }

  return files;
}

/** All code-gen tools need 55s (Vercel Hobby has 60s limit) */
const CODE_GEN_TIMEOUT = 55_000;

export const codeGenerationTools: ToolDefinition[] = [
  {
    timeoutMs: CODE_GEN_TIMEOUT,
    definition: {
      name: "generate_fullstack_app",
      description: `Generate a complete full-stack application with multiple files (React components, API routes, database migrations, tests).

Use this when the user asks to build a complex app that requires multiple files and backend logic.
Examples: "Build an e-commerce site with Stripe", "Create a habit tracker with charts", "Build a blog with authentication".

This is different from the simple Canvas app builder (build_app) which only creates single-table CRUD widgets.`,
      input_schema: {
        type: "object" as const,
        properties: {
          description: {
            type: "string",
            description: "Detailed description of the application to build",
          },
          features: {
            type: "array",
            items: { type: "string" },
            description: "List of required features",
          },
          tech_stack: {
            type: "string",
            description:
              "Technology stack to use (default: Next.js, Supabase, TailwindCSS)",
          },
        },
        required: ["description", "features"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const description = input.description as string;
      const features = input.features as string[];
      const techStack =
        (input.tech_stack as string) || "Next.js, Supabase, TailwindCSS";

      const task: CodeGenerationTask = {
        description,
        context: {
          repoSize: 0,
          fileCount: 0,
          dependencies: [
            "next",
            "react",
            "@supabase/supabase-js",
            "tailwindcss",
          ],
        },
        requirements: features,
        expectedOutput: {
          fileCount: 10,
          estimatedLines: 500,
          requiresGit: false,
          requiresDeployment: false,
        },
        tenantId,
      };

      logger.info("[CodeGenTools] Generating full-stack app:", {
        tenantId,
        description: description.slice(0, 80),
        features: features.length,
        techStack,
      });

      const result = await executeCodeGeneration(task);

      if (!result.success) {
        logger.error("[CodeGenTools] Generation failed:", {
          tenantId,
          error: result.error,
          model: result.model,
        });
        return `Nie udalo sie wygenerowac aplikacji: ${result.error || "Nieznany blad"}`;
      }

      // Store workspace + files in DB (server-side — use service client)
      try {
        const { getServiceSupabase } = await import("@/lib/supabase/service");
        const supabase = getServiceSupabase();
        const workspaceId = `ws-${tenantId.slice(0, 8)}-${Date.now()}`;

        await supabase.from("exo_code_workspaces").insert({
          id: workspaceId,
          tenant_id: tenantId,
          name: description.substring(0, 100),
          description,
          model_used: result.model,
          tech_stack: techStack,
          features: features,
          status: "generated",
          total_files: result.files.length,
          generation_duration_ms: result.duration,
        });

        // Batch insert files
        const fileRows = result.files.map((file) => ({
          workspace_id: workspaceId,
          tenant_id: tenantId,
          file_path: file.path,
          content: file.content,
          language: file.language || null,
          operation: file.operation || "create",
          version: 1,
          line_count: file.content.split("\n").length,
        }));

        if (fileRows.length > 0) {
          const { error: filesError } = await supabase
            .from("exo_generated_files")
            .insert(fileRows);
          if (filesError) {
            logger.warn(
              "[CodeGenTools] File insert warning:",
              filesError.message,
            );
          }
        }

        let response = `Wygenerowano aplikacje "${description}" (${result.files.length} plikow)\n\n`;
        response += `Workspace: ${workspaceId}\n`;
        response += `Model: ${result.model}\n`;
        response += `Czas: ${result.duration}ms\n\n`;
        if (result.summary) {
          response += `Podsumowanie: ${result.summary}\n\n`;
        }
        response += `Pliki:\n`;
        for (const file of result.files) {
          response += `  - ${file.path} (${file.language || "unknown"})\n`;
        }
        if (result.dependencies && result.dependencies.length > 0) {
          response += `\nZaleznosci: ${result.dependencies.join(", ")}\n`;
        }
        response += `\nMozesz uzyc modify_code aby zmienic pliki, run_tests aby sprawdzic, lub deploy_app aby wdrozyc.`;

        return response;
      } catch (dbError) {
        logger.error("[CodeGenTools] DB save failed:", {
          tenantId,
          error: dbError instanceof Error ? dbError.message : String(dbError),
        });
        // Still return the generation result even if DB save fails
        let response = `Wygenerowano aplikacje "${description}" (${result.files.length} plikow)\n`;
        response += `Model: ${result.model}, Czas: ${result.duration}ms\n`;
        response += `UWAGA: Nie udalo sie zapisac do bazy danych.\n\n`;
        response += `Pliki:\n`;
        for (const file of result.files.slice(0, 10)) {
          response += `  - ${file.path}\n`;
        }
        return response;
      }
    },
  },

  {
    timeoutMs: CODE_GEN_TIMEOUT,
    definition: {
      name: "modify_code",
      description: `Modify existing code files in a workspace using AI.

Use this when the user wants to change existing code.
Examples: "Add error handling to the login function", "Refactor the database query", "Update the API endpoint".`,
      input_schema: {
        type: "object" as const,
        properties: {
          workspace_id: {
            type: "string",
            description: "Workspace ID (from generate_fullstack_app)",
          },
          file_path: {
            type: "string",
            description: "Path to the file to modify",
          },
          instruction: {
            type: "string",
            description: "What to change",
          },
        },
        required: ["workspace_id", "file_path", "instruction"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const workspaceId = input.workspace_id as string;
      const filePath = input.file_path as string;
      const instruction = input.instruction as string;

      logger.info("[CodeGenTools] Modifying code:", {
        tenantId,
        workspaceId,
        filePath,
        instruction: instruction.slice(0, 80),
      });

      try {
        const { getServiceSupabase } = await import("@/lib/supabase/service");
        const supabase = getServiceSupabase();

        // Load the latest version of the file
        const { data: existingFile, error: fetchError } = await supabase
          .from("exo_generated_files")
          .select("id, content, version, language")
          .eq("workspace_id", workspaceId)
          .eq("tenant_id", tenantId)
          .eq("file_path", filePath)
          .order("version", { ascending: false })
          .limit(1)
          .single();

        if (fetchError || !existingFile) {
          return `Nie znaleziono pliku ${filePath} w workspace ${workspaceId}. Sprawdz sciezke.`;
        }

        // Use AI to modify the file
        const { buildModifyPrompt } =
          await import("@/lib/code-generation/prompts/code-gen-prompt");
        const { parseModifyResponse } =
          await import("@/lib/code-generation/response-parser");
        const { aiChat } = await import("@/lib/ai");

        const response = await aiChat(
          [
            {
              role: "user",
              content: buildModifyPrompt(
                filePath,
                existingFile.content,
                instruction,
              ),
            },
          ],
          {
            forceModel: "gemini-3.1-pro",
            maxTokens: 8192,
            tenantId,
            taskCategory: "analysis",
          },
        );

        const parsed = parseModifyResponse(response.content);
        if (!parsed || !parsed.content) {
          return `Nie udalo sie zmodyfikowac pliku. AI nie zwrocilo poprawnej odpowiedzi.`;
        }

        // Insert new version (preserving previous)
        const newVersion = (existingFile.version || 1) + 1;
        const { error: insertError } = await supabase
          .from("exo_generated_files")
          .insert({
            workspace_id: workspaceId,
            tenant_id: tenantId,
            file_path: filePath,
            content: parsed.content,
            language: existingFile.language,
            operation: "modify",
            version: newVersion,
            previous_content: existingFile.content,
            line_count: parsed.content.split("\n").length,
          });

        if (insertError) {
          logger.error(
            "[CodeGenTools] Modify save failed:",
            insertError.message,
          );
          return `Zmodyfikowano plik, ale nie udalo sie zapisac: ${insertError.message}`;
        }

        let result = `Zmodyfikowano ${filePath} (v${newVersion})\n\n`;
        result += `Instrukcja: ${instruction}\n`;
        if (parsed.summary) {
          result += `Zmiany: ${parsed.summary}\n`;
        }
        result += `Linie: ${parsed.content.split("\n").length}\n`;

        return result;
      } catch (error) {
        logger.error("[CodeGenTools] modify_code failed:", {
          tenantId,
          error: error instanceof Error ? error.message : String(error),
        });
        return `Blad modyfikacji: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
  },

  {
    timeoutMs: CODE_GEN_TIMEOUT,
    definition: {
      name: "run_tests",
      description: `Run tests and analyze code quality for a workspace.

If VPS executor is available, tests run in a real Docker sandbox (npm test, typecheck, lint).
Otherwise falls back to AI-based code review.
Examples: "Run tests for the habit tracker", "Test the API endpoints".`,
      input_schema: {
        type: "object" as const,
        properties: {
          workspace_id: {
            type: "string",
            description: "Workspace ID",
          },
        },
        required: ["workspace_id"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const workspaceId = input.workspace_id as string;

      logger.info("[CodeGenTools] Running test analysis:", {
        tenantId,
        workspaceId,
      });

      try {
        const { getServiceSupabase } = await import("@/lib/supabase/service");
        const supabase = getServiceSupabase();

        // Load all files from workspace (latest versions only)
        const { data: files, error: fetchError } = await supabase
          .from("exo_generated_files")
          .select("file_path, content, language, version")
          .eq("workspace_id", workspaceId)
          .eq("tenant_id", tenantId)
          .order("version", { ascending: false });

        if (fetchError || !files || files.length === 0) {
          return `Workspace ${workspaceId} nie zawiera plikow lub nie istnieje.`;
        }

        // Deduplicate to latest version per file
        const latestFiles = new Map<string, (typeof files)[0]>();
        for (const f of files) {
          if (!latestFiles.has(f.file_path)) {
            latestFiles.set(f.file_path, f);
          }
        }

        // Try VPS execution first (real Docker sandbox)
        const vpsAvailable = await isVPSAvailable();
        if (vpsAvailable) {
          logger.info("[CodeGenTools] VPS available — running real tests");
          const vpsFiles = Array.from(latestFiles.values()).map((f) => ({
            path: f.file_path,
            content: f.content,
          }));

          const vpsResult = await runTestsOnVPS(workspaceId, vpsFiles);

          // Update workspace status
          const status = vpsResult.success ? "vps_tested" : "test_failed";
          await supabase
            .from("exo_code_workspaces")
            .update({ status })
            .eq("id", workspaceId)
            .eq("tenant_id", tenantId);

          let result = `Testy (Docker sandbox) dla workspace ${workspaceId}\n`;
          result += `Plikow: ${latestFiles.size}\n\n`;
          result += formatVPSResult(vpsResult);
          return result;
        }

        // Fallback: AI-based analysis (no VPS)
        logger.info("[CodeGenTools] VPS not available — using AI analysis");

        const codeSummary = Array.from(latestFiles.values())
          .map(
            (f) =>
              `### ${f.file_path} (${f.language || "unknown"})\n\`\`\`\n${f.content.slice(0, 2000)}\n\`\`\``,
          )
          .join("\n\n");

        const { aiChat } = await import("@/lib/ai");
        const response = await aiChat(
          [
            {
              role: "user",
              content: `Analyze the following code files and generate a test report. For each file, identify:
1. Potential bugs or issues
2. Missing error handling
3. Security concerns
4. Test cases that should exist (with expected pass/fail)
5. Overall code quality score (1-10)

Be specific and actionable. Respond in Polish.

${codeSummary}`,
            },
          ],
          {
            forceModel: "gemini-3.1-pro",
            maxTokens: 4096,
            tenantId,
            taskCategory: "analysis",
          },
        );

        let result = `Analiza testow (AI) dla workspace ${workspaceId}\n`;
        result += `Przeanalizowano ${latestFiles.size} plikow\n`;
        result += `(VPS niedostepny — analiza AI zamiast prawdziwych testow)\n\n`;
        result += response.content;

        // Update workspace status
        await supabase
          .from("exo_code_workspaces")
          .update({ status: "tested" })
          .eq("id", workspaceId)
          .eq("tenant_id", tenantId);

        return result;
      } catch (error) {
        logger.error("[CodeGenTools] run_tests failed:", {
          tenantId,
          error: error instanceof Error ? error.message : String(error),
        });
        return `Blad analizy testow: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
  },

  {
    timeoutMs: CODE_GEN_TIMEOUT,
    definition: {
      name: "deploy_app",
      description: `Deploy a workspace to production. Supports Vercel, Railway, VPS Docker, or manual instructions.

Examples: "Deploy the habit tracker", "Push to production", "Deploy to Railway".`,
      input_schema: {
        type: "object" as const,
        properties: {
          workspace_id: {
            type: "string",
            description: "Workspace ID",
          },
          platform: {
            type: "string",
            enum: ["vercel", "railway", "vps", "manual"],
            description:
              "Deployment platform (vercel, railway, vps for Docker deploy, or manual instructions)",
          },
        },
        required: ["workspace_id"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const workspaceId = input.workspace_id as string;
      const platform = (input.platform as string) || "vercel";

      logger.info("[CodeGenTools] Deploying workspace:", {
        tenantId,
        workspaceId,
        platform,
      });

      try {
        const { getServiceSupabase } = await import("@/lib/supabase/service");
        const supabase = getServiceSupabase();

        // Load workspace + files
        const { data: workspace, error: wsError } = await supabase
          .from("exo_code_workspaces")
          .select("*")
          .eq("id", workspaceId)
          .eq("tenant_id", tenantId)
          .single();

        if (wsError || !workspace) {
          return `Workspace ${workspaceId} nie istnieje lub nie masz dostepu.`;
        }

        const { data: files } = await supabase
          .from("exo_generated_files")
          .select("file_path, content")
          .eq("workspace_id", workspaceId)
          .eq("tenant_id", tenantId)
          .order("version", { ascending: false });

        if (!files || files.length === 0) {
          return `Workspace ${workspaceId} nie zawiera plikow.`;
        }

        // Deduplicate to latest version
        const latestFiles = new Map<string, string>();
        for (const f of files) {
          if (!latestFiles.has(f.file_path)) {
            latestFiles.set(f.file_path, f.content);
          }
        }

        // Try VPS deploy
        if (platform === "vps") {
          const vpsAvailable = await isVPSAvailable();
          if (!vpsAvailable) {
            return "VPS executor niedostepny. Sprawdz VPS_EXECUTOR_URL i VPS_EXECUTOR_SECRET w .env, lub uzyj platform=vercel.";
          }

          const vpsFiles = Array.from(latestFiles.entries()).map(
            ([path, content]) => ({ path, content }),
          );

          // First: build
          const buildResult = await executeOnVPS({
            workspace_id: workspaceId,
            action: "build",
            runtime: "node",
            files: vpsFiles,
            timeout_ms: 180_000, // 3min for build
            network: true,
          });

          if (!buildResult.success) {
            return `Build nie powiodl sie:\n${formatVPSResult(buildResult)}`;
          }

          // Update workspace
          await supabase
            .from("exo_code_workspaces")
            .update({
              status: "vps_deployed",
              deployment_url: `vps://${workspaceId}`,
            })
            .eq("id", workspaceId)
            .eq("tenant_id", tenantId);

          let result = `Zbudowano na VPS: workspace ${workspaceId}\n\n`;
          result += formatVPSResult(buildResult);
          return result;
        }

        // Try Railway deploy
        if (platform === "railway") {
          const railwayToken = process.env.RAILWAY_TOKEN;
          if (!railwayToken) {
            return "RAILWAY_TOKEN nie jest skonfigurowany. Dodaj go do .env lub uzyj configure_infra aby uzyskac instrukcje.";
          }

          try {
            const createProjectQuery = `mutation { projectCreate(input: { name: "${workspaceId}" }) { id name } }`;

            const projectRes = await fetch(
              "https://backboard.railway.com/graphql/v2",
              {
                method: "POST",
                headers: {
                  Authorization: `Bearer ${railwayToken}`,
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({ query: createProjectQuery }),
                signal: AbortSignal.timeout(15000),
              },
            );

            if (!projectRes.ok) {
              const errBody = await projectRes.text();
              return `Railway deployment failed: ${projectRes.status}. ${errBody.slice(0, 200)}`;
            }

            const projectData = await projectRes.json();
            const projectId = projectData?.data?.projectCreate?.id;

            if (!projectId) {
              return "Railway: nie udalo sie utworzyc projektu. Sprawdz token.";
            }

            const projectUrl = `https://railway.com/project/${projectId}`;

            await supabase
              .from("exo_code_workspaces")
              .update({
                status: "deployed",
                deployment_url: projectUrl,
              })
              .eq("id", workspaceId)
              .eq("tenant_id", tenantId);

            let result = `Utworzono projekt Railway: ${workspaceId}\n\n`;
            result += `URL: ${projectUrl}\n`;
            result += `Pliki: ${latestFiles.size}\n`;
            result += `\nNastepne kroki: podlacz repo Git do Railway aby wdrozyc kod.`;

            return result;
          } catch (railwayError) {
            logger.error("[CodeGenTools] Railway API error:", railwayError);
            return `Blad Railway API: ${railwayError instanceof Error ? railwayError.message : String(railwayError)}`;
          }
        }

        const vercelToken = process.env.VERCEL_TOKEN;

        if (platform === "vercel" && vercelToken) {
          // Deploy via Vercel API
          try {
            const fileEntries = Array.from(latestFiles.entries()).map(
              ([path, content]) => ({
                file: path,
                data: content,
              }),
            );

            const deployRes = await fetch(
              "https://api.vercel.com/v13/deployments",
              {
                method: "POST",
                headers: {
                  Authorization: `Bearer ${vercelToken}`,
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({
                  name: workspaceId,
                  files: fileEntries,
                  projectSettings: {
                    framework: "nextjs",
                  },
                }),
                signal: AbortSignal.timeout(30000),
              },
            );

            if (!deployRes.ok) {
              const errBody = await deployRes.text();
              logger.error("[CodeGenTools] Vercel deploy failed:", errBody);
              return `Vercel deployment failed: ${deployRes.status}. Sprobuj ponownie lub uzyj "manual".`;
            }

            const deployData = await deployRes.json();
            const deploymentUrl = deployData.url
              ? `https://${deployData.url}`
              : null;

            // Update workspace
            await supabase
              .from("exo_code_workspaces")
              .update({
                status: "deployed",
                deployment_url: deploymentUrl,
              })
              .eq("id", workspaceId)
              .eq("tenant_id", tenantId);

            let result = `Wdrozono workspace ${workspaceId} na Vercel\n\n`;
            if (deploymentUrl) {
              result += `URL: ${deploymentUrl}\n`;
            }
            result += `Pliki: ${latestFiles.size}\n`;
            result += `Status: deployed\n`;

            return result;
          } catch (deployError) {
            logger.error("[CodeGenTools] Vercel API error:", {
              error:
                deployError instanceof Error
                  ? deployError.message
                  : String(deployError),
            });
            return `Blad Vercel API: ${deployError instanceof Error ? deployError.message : String(deployError)}. Sprobuj platform=manual.`;
          }
        }

        // Manual deployment instructions
        let result = `Instrukcje wdrozenia dla workspace ${workspaceId}\n\n`;
        result += `Pliki (${latestFiles.size}):\n`;
        for (const [path] of latestFiles) {
          result += `  - ${path}\n`;
        }
        result += `\nKroki:\n`;
        result += `1. Utworz nowy projekt: npx create-next-app@latest ${workspaceId}\n`;
        result += `2. Skopiuj wygenerowane pliki do projektu\n`;
        result += `3. Zainstaluj zaleznosci: npm install\n`;
        result += `4. Uruchom lokalnie: npm run dev\n`;
        result += `5. Deploy: vercel --prod\n`;

        if (!vercelToken) {
          result += `\nUWAGA: VERCEL_TOKEN nie jest skonfigurowany. Dodaj go do .env aby umozliwic automatyczny deploy.`;
        }

        // Update workspace status
        await supabase
          .from("exo_code_workspaces")
          .update({ status: "ready_to_deploy" })
          .eq("id", workspaceId)
          .eq("tenant_id", tenantId);

        return result;
      } catch (error) {
        logger.error("[CodeGenTools] deploy_app failed:", {
          tenantId,
          error: error instanceof Error ? error.message : String(error),
        });
        return `Blad wdrozenia: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
  },

  {
    timeoutMs: 120_000, // 2min for VPS execution
    definition: {
      name: "execute_code",
      description: `Execute code in a secure Docker sandbox on the VPS.

Run scripts, test snippets, or execute programs in isolated containers.
Supports Node.js and Python runtimes.
Examples: "Run this Python script", "Execute the data processing pipeline", "Test this function".

Requires VPS executor to be configured (VPS_EXECUTOR_URL).`,
      input_schema: {
        type: "object" as const,
        properties: {
          code: {
            type: "string",
            description: "Code to execute",
          },
          filename: {
            type: "string",
            description: "Filename for the code (e.g., 'main.py', 'script.ts')",
          },
          runtime: {
            type: "string",
            enum: ["node", "python"],
            description: "Runtime environment (default: node)",
          },
          command: {
            type: "string",
            description: "Custom command to run (overrides default)",
          },
          additional_files: {
            type: "array",
            items: {
              type: "object",
              properties: {
                path: { type: "string" },
                content: { type: "string" },
              },
              required: ["path", "content"],
            },
            description:
              "Additional files needed (e.g., package.json, requirements.txt)",
          },
        },
        required: ["code", "filename"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const code = input.code as string;
      const filename = input.filename as string;
      const runtime = (input.runtime as "node" | "python") || "node";
      const command = input.command as string | undefined;
      const additionalFiles =
        (input.additional_files as Array<{ path: string; content: string }>) ||
        [];

      logger.info("[CodeGenTools] execute_code:", {
        tenantId,
        filename,
        runtime,
        codeLength: code.length,
      });

      const vpsAvailable = await isVPSAvailable();
      if (!vpsAvailable) {
        return "VPS executor niedostepny. Nie mozna uruchomic kodu. Skonfiguruj VPS_EXECUTOR_URL i VPS_EXECUTOR_SECRET w .env.";
      }

      const files = [{ path: filename, content: code }, ...additionalFiles];

      const result = await executeOnVPS({
        action: "run",
        runtime,
        files,
        entrypoint: filename,
        command,
        timeout_ms: 60_000,
        network: false, // Sandbox: no outbound network by default
      });

      return formatVPSResult(result);
    },
  },

  {
    timeoutMs: 300_000, // 5min — full build cycle can take a while
    definition: {
      name: "build_and_deploy",
      description: `Build a complete full-stack application with iterative testing and optional deployment.

Unlike generate_fullstack_app (single pass), this tool:
1. Generates the app
2. Runs tests in Docker sandbox
3. If tests fail → AI fixes errors → re-tests (up to 3 iterations)
4. Optionally deploys to Vercel/Railway/VPS

Use for complex apps where quality matters. Examples: "Build and deploy a CRM", "Create a project management tool and put it live".`,
      input_schema: {
        type: "object" as const,
        properties: {
          description: {
            type: "string",
            description: "Detailed description of the application",
          },
          features: {
            type: "array",
            items: { type: "string" },
            description: "Required features",
          },
          tech_stack: {
            type: "string",
            description: "Tech stack (default: Next.js + Supabase + Tailwind)",
          },
          auto_deploy: {
            type: "boolean",
            description:
              "Deploy automatically after tests pass (default: false)",
          },
          deploy_target: {
            type: "string",
            enum: ["vercel", "railway", "vps"],
            description: "Where to deploy (default: vercel)",
          },
          max_iterations: {
            type: "number",
            description: "Max test→fix cycles (default: 3)",
          },
        },
        required: ["description", "features"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const description = input.description as string;
      const features = input.features as string[];

      logger.info("[CodeGenTools] build_and_deploy:", {
        tenantId,
        description: description.slice(0, 80),
        features: features.length,
        autoDeploy: !!input.auto_deploy,
      });

      const result = await buildFullStackApp({
        tenantId,
        description,
        features,
        techStack: input.tech_stack as string | undefined,
        maxIterations: (input.max_iterations as number) || 3,
        autoDeploy: !!input.auto_deploy,
        deployTarget:
          (input.deploy_target as "vercel" | "railway" | "vps") || "vercel",
      });

      let response = "";
      if (result.success) {
        response += `Zbudowano aplikacje "${description}"\n\n`;
        response += `Workspace: ${result.workspaceId}\n`;
        response += `Model: ${result.model}\n`;
        response += `Iteracje: ${result.iterations}\n`;
        response += `Testy: ${result.testsPassed ? "PASS" : "nie uruchomione (brak VPS)"}\n`;
        response += `Czas: ${Math.round(result.duration / 1000)}s\n`;
        response += `Pliki: ${result.files.length}\n`;
        if (result.deploymentUrl) {
          response += `Deploy: ${result.deploymentUrl}\n`;
        }
        response += `\nPliki:\n`;
        for (const f of result.files) {
          response += `  - ${f.path}\n`;
        }
      } else {
        response += `Budowanie nie powiodlo sie: "${description}"\n\n`;
        response += `Model: ${result.model}\n`;
        response += `Iteracje: ${result.iterations}\n`;
        if (result.errors.length > 0) {
          response += `\nBledy:\n`;
          for (const err of result.errors) {
            response += `  - ${err}\n`;
          }
        }
      }

      return response;
    },
  },

  {
    timeoutMs: 10_000,
    definition: {
      name: "configure_infra",
      description: `Check infrastructure status and get setup guides for external services.

Services: supabase, vercel, railway, stripe, domain, vps.
Use "overview" to see all services status, or specify a service name for step-by-step guide.

Examples: "Check infra status", "How to set up Stripe", "Guide me through Supabase setup".`,
      input_schema: {
        type: "object" as const,
        properties: {
          service: {
            type: "string",
            enum: [
              "overview",
              "supabase",
              "vercel",
              "railway",
              "stripe",
              "domain",
              "vps",
            ],
            description:
              "Which service to configure (use 'overview' for status of all)",
          },
        },
        required: ["service"],
      },
    },
    execute: async (input: Record<string, unknown>): Promise<string> => {
      const service = input.service as string;

      if (service === "overview") {
        return formatInfraOverview();
      }

      const guide = getInfraGuide(service as InfraService);
      return formatInfraGuide(guide);
    },
  },

  {
    timeoutMs: CODE_GEN_TIMEOUT,
    definition: {
      name: "create_project",
      description: `Initialize a new project from a template with boilerplate code.

Generates a complete project scaffold with:
- Next.js app with TypeScript
- Supabase integration (auth + database)
- TailwindCSS styling
- Basic pages (home, login, dashboard)
- API routes template
- Environment configuration

Use before generate_fullstack_app when starting a brand new project.
Examples: "Start a new Next.js project", "Initialize a new app with auth".`,
      input_schema: {
        type: "object" as const,
        properties: {
          name: {
            type: "string",
            description: "Project name (slug format, e.g., 'my-crm-app')",
          },
          template: {
            type: "string",
            enum: ["nextjs-supabase", "nextjs-minimal", "api-only"],
            description: "Template to use (default: nextjs-supabase)",
          },
          features: {
            type: "array",
            items: { type: "string" },
            description:
              "Initial features to include (auth, dashboard, api, etc.)",
          },
        },
        required: ["name"],
      },
    },
    execute: async (
      input: Record<string, unknown>,
      tenantId: string,
    ): Promise<string> => {
      const name = input.name as string;
      const template = (input.template as string) || "nextjs-supabase";
      const features = (input.features as string[]) || ["auth", "dashboard"];

      logger.info("[CodeGenTools] create_project:", {
        tenantId,
        name,
        template,
      });

      const scaffoldFiles = generateScaffold(name, template, features);

      // Save to DB as a workspace
      try {
        const { getServiceSupabase } = await import("@/lib/supabase/service");
        const supabase = getServiceSupabase();
        const workspaceId = `ws-${tenantId.slice(0, 8)}-${Date.now()}`;

        await supabase.from("exo_code_workspaces").insert({
          id: workspaceId,
          tenant_id: tenantId,
          name,
          description: `Project scaffold: ${template}`,
          model_used: "template",
          tech_stack: template,
          features,
          status: "generated",
          total_files: scaffoldFiles.length,
          generation_duration_ms: 0,
        });

        const fileRows = scaffoldFiles.map((f) => ({
          workspace_id: workspaceId,
          tenant_id: tenantId,
          file_path: f.path,
          content: f.content,
          language: f.language || null,
          operation: "create" as const,
          version: 1,
          line_count: f.content.split("\n").length,
        }));

        await supabase.from("exo_generated_files").insert(fileRows);

        let response = `Utworzono projekt "${name}" (template: ${template})\n\n`;
        response += `Workspace: ${workspaceId}\n`;
        response += `Pliki: ${scaffoldFiles.length}\n\n`;
        for (const f of scaffoldFiles) {
          response += `  - ${f.path}\n`;
        }
        response += `\nUzyj generate_fullstack_app lub modify_code aby dodac funkcjonalnosci.`;
        response += `\nUzyj deploy_app aby wdrozyc.`;

        return response;
      } catch (error) {
        logger.error("[CodeGenTools] create_project DB error:", error);
        return `Blad tworzenia projektu: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
  },
];
